In [1]:
!pip install --upgrade tensorflow tensorflow-probability h5py ezsmdeploy==1.1.4 --quiet

In [2]:
import numpy as np

import tensorflow.compat.v2 as tf
tf.enable_v2_behavior()

import tensorflow_probability as tfp

%matplotlib inline

tfd = tfp.distributions

2023-06-22 20:46:58.953997: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


### Create Sample Data

In [3]:
w0 = 0.125
b0 = 5.
x_range = [-20, 60]

def load_dataset(n=150, n_tst=150):
  np.random.seed(43)
  def s(x):
    g = (x - x_range[0]) / (x_range[1] - x_range[0])
    return 3 * (0.25 + g**2.)
  x = (x_range[1] - x_range[0]) * np.random.rand(n) + x_range[0]
  eps = np.random.randn(n) * s(x)
  y = (w0 * x * (1. + np.sin(x)) + b0) + eps
  x = x[..., np.newaxis]
  x_tst = np.linspace(*x_range, num=n_tst).astype(np.float32)
  x_tst = x_tst[..., np.newaxis]
  return y, x, x_tst

y, x, x_tst = load_dataset()

### Build model

In [4]:
# Build model.
negloglik = lambda y, rv_y: -rv_y.log_prob(y)
model = tf.keras.Sequential([
  tf.keras.layers.Dense(1 + 1),
  tfp.layers.DistributionLambda(
      lambda t: tfd.Normal(loc=t[..., :1],
                           scale=1e-3 + tf.math.softplus(0.05 * t[...,1:]))),
])

# Do inference.
model.compile(optimizer=tf.optimizers.Adam(learning_rate=0.01), loss=negloglik)
model.fit(x, y, epochs=1000, verbose=False);

# Profit.
[print(np.squeeze(w.numpy())) for w in model.weights];
yhat = model(x_tst)
assert isinstance(yhat, tfd.Distribution)

2023-06-22 20:47:03.858526: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-06-22 20:47:03.858585: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-16-69-48.ec2.internal): /proc/driver/nvidia/version does not exist
2023-06-22 20:47:03.859486: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
[ 0.18431081 -0.02869033]
[2.8829193 1.2902781]


In [5]:
model(x_tst)

<tfp.distributions._TensorCoercible 'tensor_coercible' batch_shape=[150, 1] event_shape=[] dtype=float32>

In [6]:
model.predict(x_tst) # <--- this is what happens internally. It returns a tensor instead of a distribution we can sample from

5/5 [==============================] - 0s 1ms/step


array([[-0.5412204 ],
       [-1.9410728 ],
       [-0.578021  ],
       [-0.16698971],
       [-1.468133  ],
       [-0.50508   ],
       [-0.38154763],
       [-0.6259771 ],
       [ 0.34351516],
       [-0.12712643],
       [ 0.48169196],
       [ 0.29946333],
       [-0.42862403],
       [ 1.1576133 ],
       [ 1.5853112 ],
       [ 0.67053574],
       [ 0.1256119 ],
       [ 0.63639003],
       [ 2.2690997 ],
       [ 1.9389335 ],
       [ 1.6570092 ],
       [ 2.354652  ],
       [ 1.7384638 ],
       [ 1.1579847 ],
       [ 0.7559252 ],
       [ 0.76515126],
       [ 3.2890768 ],
       [ 2.1942217 ],
       [ 2.2424335 ],
       [ 1.9871    ],
       [ 2.1922774 ],
       [ 1.9778376 ],
       [ 2.3436756 ],
       [ 3.4921634 ],
       [ 1.6523192 ],
       [ 3.1811779 ],
       [ 3.4734967 ],
       [ 2.1260653 ],
       [ 3.5958407 ],
       [ 2.9439008 ],
       [ 3.6507337 ],
       [ 3.6144187 ],
       [ 2.8634152 ],
       [ 3.6932554 ],
       [ 3.853349  ],
       [ 3

In [7]:
# model.save('model1.h5')

_This method of saving has some problems..._

In [8]:
import h5py

In [9]:
!rm -r models
!mkdir models

rm: cannot remove ‘models’: No such file or directory


In [10]:
model_name = 'reg1'
file = h5py.File('{}.h5'.format(model_name), 'w')
weight = model.get_weights()
for i in range(len(weight)):
    file.create_dataset('weight' + str(i), data=weight[i])
file.close()

In [11]:
negloglik = lambda y, rv_y: -rv_y.log_prob(y)
newmodel = tf.keras.Sequential([
  tf.keras.layers.Dense(1 + 1),
  tfp.layers.DistributionLambda(
      lambda t: tfd.Normal(loc=t[..., :1],
                           scale=1e-3 + tf.math.softplus(0.05 * t[...,1:]))),
])

In [12]:
x_tst.shape

(150, 1)

### Reload model to see if it is saved correctly

In [13]:
file = h5py.File('{}.h5'.format(model_name), 'r')
weight = []
for i in range(len(file.keys())):
   weight.append(file['weight' + str(i)][:])

newmodel.build(input_shape = (150,1))
newmodel.set_weights(weight)

In [14]:
y_tst = newmodel(x_tst)

In [15]:
y_tst.__dict__

{'_parameters': {'loc': <tf.Tensor: shape=(150, 1), dtype=float32, numpy=
  array([[-8.03296804e-01],
         [-7.04338074e-01],
         [-6.05379105e-01],
         [-5.06420374e-01],
         [-4.07461405e-01],
         [-3.08502674e-01],
         [-2.09544182e-01],
         [-1.10585213e-01],
         [-1.16262436e-02],
         [ 8.73324871e-02],
         [ 1.86291218e-01],
         [ 2.85250187e-01],
         [ 3.84208918e-01],
         [ 4.83167887e-01],
         [ 5.82126856e-01],
         [ 6.81085348e-01],
         [ 7.80044317e-01],
         [ 8.79003048e-01],
         [ 9.77962017e-01],
         [ 1.07692087e+00],
         [ 1.17587972e+00],
         [ 1.27483833e+00],
         [ 1.37379718e+00],
         [ 1.47275603e+00],
         [ 1.57171488e+00],
         [ 1.67067373e+00],
         [ 1.76963258e+00],
         [ 1.86859143e+00],
         [ 1.96755016e+00],
         [ 2.06650901e+00],
         [ 2.16546774e+00],
         [ 2.26442671e+00],
         [ 2.36338544e+00],
  

## Try with Ezsmdeploy

In [16]:
%%writefile tfp_predict_script.py
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
import json
import h5py
import os
tfd = tfp.distributions

#Return loaded model
def load_model(modelpath):

    # (re)Defne model
    negloglik = lambda y, rv_y: -rv_y.log_prob(y)
    model = tf.keras.Sequential([
      tf.keras.layers.Dense(1 + 1),
      tfp.layers.DistributionLambda(
          lambda t: tfd.Normal(loc=t[..., :1],
                               scale=1e-3 + tf.math.softplus(0.05 * t[...,1:]))),
    ])


    # Load model
    print("1. Listing files in modelpath")
    print(os.listdir(modelpath))
    
    print("2. Loading h5 file")
    file = h5py.File(os.path.join(modelpath,'reg1.h5'), 'r')
    
    print("3. Loading weights")
    weight = []
    for i in range(len(file.keys())):
       weight.append(file['weight' + str(i)][:])

    model.build(input_shape = (150,1))
    model.set_weights(weight)
    
    print("4. Loaded model successfully")
    
    return model

# return prediction based on loaded model (from the step above) and an input payload
def predict(model, payload):
    try:
        # Note, for Multi model endpoints -> (payload[0]['body'].decode())
        data = np.frombuffer(payload,dtype=np.float32).reshape((150,1))
        tmpout = model(data)
        
        #Add outputs here !!
        
        out = {
            'mean':np.asarray(tmpout.mean()).T.tolist(),
            'mode':np.asarray(tmpout.mode()).T.tolist(),
            'stddev':np.asarray(tmpout.stddev()).T.tolist(),
            'quantile_75':np.asarray(tmpout.quantile(0.75)).T.tolist()
            }
                                     
    except Exception as e:
        out = str(e)
    return [json.dumps({'output':out})]

Writing tfp_predict_script.py


## Does this work Locally in the notebook?

In [17]:
from tfp_predict_script import *
model = load_model('./')

1. Listing files in modelpath
['reg1.h5', 'mobilenet_v1_1.0_224_quant.tflite', '.ipynb_checkpoints', '__pycache__', 'modelscript_sklearn.py', 'labels_mobilenet_quant_v1_224.txt', 'modelscript_pytorch.py', 'Using ezsmdeploy for sklearn ensemble deployments.ipynb', 'Using ezsmdeploy for mxnet deployments.ipynb', 'src', 'input.html', 'model1.tar.gz', 'tmpmodel', 'extractedmodel', 'svm.joblib', 'downloads', 'cart.joblib', 'tfp_predict_script.py', 'Using ezsmdeploy for tensorflow deployments.ipynb', 'tensorflow-serving-TF-probability-python-sdk.ipynb', 'modelscript_ensemble_sklearn.py', 'logistic.joblib', 'model2.tar.gz', 'model.tar.gz', 'modelscript_mxnet.py', 'Using ezsmdeploy for tensorflow lite deployments.ipynb', 'modelscript_tensorflow.py', 'ensemble.joblib', 'models', 'dog-1.jpg', 'modelscript_tensorflow_lite.py', 'Using ezsmdeploy for pytorch deployments.ipynb', 'Using ezsmdeploy for sklearn deployments.ipynb', 'model.pth']
2. Loading h5 file
3. Loading weights
4. Loaded model succe

In [18]:
predict(model,x_tst.tobytes())

['{"output": {"mean": [[-0.8032968044281006, -0.7043380737304688, -0.6053791046142578, -0.506420373916626, -0.40746140480041504, -0.3085026741027832, -0.20954418182373047, -0.11058521270751953, -0.011626243591308594, 0.08733248710632324, 0.18629121780395508, 0.285250186920166, 0.38420891761779785, 0.4831678867340088, 0.5821268558502197, 0.6810853481292725, 0.7800443172454834, 0.8790030479431152, 0.9779620170593262, 1.0769208669662476, 1.175879716873169, 1.2748383283615112, 1.3737971782684326, 1.472756028175354, 1.5717148780822754, 1.6706737279891968, 1.7696325778961182, 1.8685914278030396, 1.9675501585006714, 2.0665090084075928, 2.1654677391052246, 2.2644267082214355, 2.3633854389190674, 2.4623444080352783, 2.56130313873291, 2.660261869430542, 2.759220838546753, 2.8581795692443848, 2.9571385383605957, 3.0560972690582275, 3.1550559997558594, 3.2540149688720703, 3.352973699569702, 3.451932430267334, 3.550891399383545, 3.6498501300811768, 3.7488090991973877, 3.8477678298950195, 3.94672679

## Deploy locally in a container

In [19]:
import ezsmdeploy

Match versions used in your notebook to make sure the endpoint deploys correctly!

In [20]:
# !pip show numpy tensorflow tensorflow-probability  h5py

In [21]:
ez = ezsmdeploy.Deploy(model = 'reg1.h5', 
                  script = 'tfp_predict_script.py',
                  requirements = ['numpy','tensorflow>=2.5','tensorflow-probability','h5py'], #or pass in the path to requirements.txt
                  instance_type = 'local',
                  wait = True)

0:00:00.003546 | compressed model(s)
0:00:00.095385 | uploaded model tarball(s) ; check returned modelpath
0:00:00.095838 | added requirements file
0:00:00.097071 | added source file
0:00:00.097974 | added Dockerfile
0:00:00.099575 | added model_handler and docker utils
0:00:00.099654 | building docker container
∙∙∙ 

WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store



∙∙∙ 

Sending build context to Docker daemon  19.97kB
Step 1/16 : FROM ubuntu:18.04
18.04: Pulling from library/ubuntu
7c457f213c76: Pulling fs layer
7c457f213c76: Verifying Checksum
7c457f213c76: Download complete
7c457f213c76: Pull complete
Digest: sha256:152dc042452c496007f07ca9127571cb9c29697f42acbfad72324b2bb2e43c98
Status: Downloaded newer image for ubuntu:18.04
 ---> f9a80a55f492
Step 2/16 : RUN apt -y update && apt -y upgrade &&     apt-get -y install curl &&     curl -sL https://deb.nodesource.com/setup_12.x | bash - &&     apt install nodejs -y &&     npm install -g @bazel/bazelisk
 ---> Running in ec7514646d7c


Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:

0:02:55.358670 | built docker container
2m∙∙∙ 

update_endpoint is a no-op in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.


0:02:55.733747 | created model(s). Now deploying on local
∙∙∙ 

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/sagemaker/local/image.py", line 627, in run
    _stream_output(self.process)
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/sagemaker/local/image.py", line 687, in _stream_output
    raise RuntimeError("Process exited with code: %s" % exit_code)
RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/sagemaker/local/image.py", line 632, in run
    raise RuntimeError(msg)
RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmpbd_2tvgi/docker-compose.yaml', '

2m●∙∙ 

RuntimeError: Giving up, endpoint didn't launch correctly

Debug any docker build instructions

In [ ]:
# !./src/build-docker.sh test

In [ ]:
out = ez.predictor.predict(x_tst.tobytes()).decode()
out

## Great! Now deploy onto a SageMaker endpoint

In [ ]:
ezonsm = ezsmdeploy.Deploy(model = 'reg1.h5', 
                  script = 'tfp_predict_script.py',
                  requirements = ['numpy','tensorflow>=2.5','tensorflow-probability','h5py'], #or pass in the path to requirements.txt
                  instance_type = 'ml.m4.xlarge', #... or let ezsmdeploy decide instance type based on model size
                  wait = True)

In [ ]:
out = ezonsm.predictor.predict(x_tst.tobytes()).decode()
out

# Cleanup

To avoid incurring charges due to a stray endpoint, delete the Amazon SageMaker endpoint if you no longer need it:

In [ ]:
ezonsm.predictor.delete_endpoint()